// Integration test of two clients. The DOM, player and authenticated transport are simulated.
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
class Element{constructor(){this.value='';this.textContent='';this.children=[];this.hidden=false;this.disabled=false;this.classList={toggle(){},add(){}};}append(...c){this.children.push(...c)}replaceChildren(...c){this.children=c}setAttribute(){} }
class Events{constructor(){this.handlers={}}on(t,f){(this.handlers[t]??=[]).push(f);return this}emit(t,v){for(const f of this.handlers[t]||[])f(v)}}
const hub=new Map();class Channel extends Events{constructor(){super();this.open=true}send(p){const data=structuredClone(p);setTimeout(()=>{if(this.other.open)this.other.emit('data',data)},0)}close(){if(!this.open)return;this.open=false;this.emit('close');if(this.other.open){this.other.open=false;this.other.emit('close')}}}
class Peer extends Events{static async getUser(){return {uid:'tester',displayName:'친구'}}constructor(id){super();this.id=id;this.cs=[];hub.set(id,this);setTimeout(()=>this.emit('open',id),0)}connect(id){const a=new Channel(),b=new Channel();a.other=b;b.other=a;this.cs.push(a);const h=hub.get(id);h.cs.push(b);h.emit('connection',b);setTimeout(()=>a.emit('open'),0);return a}destroy(){hub.delete(this.id);for(const c of this.cs)c.close()}}
function client(){const els=new Map();for(const m of fs.readFileSync('sync-music.html','utf8').matchAll(/id="([^"]+)"/g))els.set(m[1],new Element());const timers=[];let player;const doc={getElementById:id=>els.get(id),createElement:()=>new Element(),createTextNode:t=>({textContent:t}),head:new Element(),addEventListener(){}};
const c={document:doc,URL,performance,crypto:webcrypto,console,FirebaseRoomPeer:Peer,firebase:{auth:()=>({onAuthStateChanged:f=>f({uid:'tester'})})},location:{href:'https://example.test/sync-music.html',origin:'https://example.test'},history:{replaceState(_a,_b,u){c.location.href=u.href}},navigator:{clipboard:{writeText:async()=>{}}},confirm:()=>true,setTimeout:(f,t)=>{const h=setTimeout(f,t);h.unref();timers.push(h);return h},clearTimeout,setInterval:(f,t)=>{const h=setInterval(f,t);h.unref();timers.push(h);return h},clearInterval,addEventListener(){}};
c.window=c;c.YT={Player:class{constructor(_id,o){player=this;this.o=o;this.id='';this.s=5;this.pos=0;setTimeout(()=>o.events.onReady(),0)}getCurrentTime(){return this.pos}getDuration(){return 240}getVideoData(){return {video_id:this.id}}getPlayerState(){return this.s}event(s){this.s=s;setTimeout(()=>this.o.events.onStateChange({data:s}),0)}cueVideoById(v){this.id=v.videoId;this.pos=v.startSeconds;this.event(5)}loadVideoById(v){this.id=v.videoId;this.pos=v.startSeconds;this.event(1)}playVideo(){this.event(1)}pauseVideo(){this.event(2)}stopVideo(){this.event(5)}seekTo(p){this.pos=p}unMute(){}}};
vm.createContext(c);vm.runInContext(fs.readFileSync('sync-music-core.js','utf8'),c);vm.runInContext(fs.readFileSync('sync-music.js','utf8'),c);c.onYouTubeIframeAPIReady();return {c,els,get player(){return player},click:id=>els.get(id).onclick(),form:id=>els.get(id).onsubmit({preventDefault(){}}),stop:()=>timers.forEach(clearTimeout)};}
const wait=()=>new Promise(r=>setTimeout(r,35));
(async()=>{const h=client(),g=client();await wait();h.click('createRoom');await wait();assert.equal(h.els.get('lobby').hidden,false);
h.els.get('videoUrl').value='https://youtu.be/abcdefghijk';h.els.get('videoTitle').value='첫곡';h.form('addForm');await wait();
g.els.get('joinCode').value=new URL(h.c.location.href).searchParams.get('room');g.click('joinRoom');await wait();await wait();assert.equal(g.els.get('nowTitle').textContent,'첫곡');assert(g.els.get('hostControls').hidden);
h.click('listen');g.click('listen');await wait();await wait();assert.equal(g.player.s,1);
h.player.pos=80;h.click('resync');await wait();assert(Math.abs(g.player.pos-80)<2);
h.click('pause');await wait();await wait();assert.equal(g.player.s,2);
g.els.get('videoUrl').value='https://youtu.be/123456789ab';g.form('addForm');await wait();assert.equal(h.els.get('queue').children.length,2);
g.els.get('chatInput').value='<img src=x onerror=alert(1)>';g.form('chatForm');await wait();assert.equal(h.els.get('chatLog').children[0].children[1].textContent,'<img src=x onerror=alert(1)>');
// A guest packet cannot replace host playback state.
const guestPeer=[...hub.values()].find(p=>p.id.includes('guest-'));guestPeer.cs[0].send({app:'vsphere-sync-music-1',type:'state',state:{current:null}});await wait();assert.equal(h.els.get('nowTitle').textContent,'첫곡');
h.click('next');await wait();await wait();assert.equal(g.player.id,'123456789ab');assert(g.player.pos<2);
h.click('leaveRoom');await wait();assert.equal(g.els.get('setup').hidden,false);h.stop();g.stop();console.log('PASS: two-client join, play, seek, pause, guest queue/chat, safe text, rejected guest controls, next-track position, room close (simulated transport/player).');})().catch(e=>{console.error(e);process.exitCode=1});
